### ISSUE TITLE
use mouse?

### ISSUE THREAD

**Issue by kuwoh** [FWGS/xash3d-android-project#112]
is it possible to use mouse in-game?

device info:
Samsung Galaxy S2 i9100
Android 2.3.3

**Comment by kuwoh** [comment]
is it possible to use mouse in-game?

device info:
Samsung Galaxy S2 i9100
Android 2.3.3

**Comment by a1batross** [comment]
Only on rooted devices.

**Comment by kuwoh** [comment]
is there anyway to use one on non-rooted devices?

**Comment by a1batross** [comment]
Nope.
We are sorry about that, but it's an issue of Android itself.

**Comment by Jan200101** [comment]
There is a way of tracking the mouse actually
That doesnt need root.

**Comment by a1batross** [comment]
You may implement it. But this will not help such games cs16-cliemt, where
it's locked due to disbalance.

10 авг. 2016 г. 1:18 пользователь "Jan200101" <notifications@github.com>
написал:

**Comment by mittorn** [comment]
>There is a way of tracking the mouse actually
>That doesnt need root.
What way?
Android only repots absolute pointer coordinates, not relative axes. Pointer is locked in screen bounds, so it is impossible to use it to camera look.
It is only possible to use API extension on NVIDIA Tegra devices, but it is vendor specific.

**Comment by Jan200101** [comment]
Well it doesnt work for every Android because it only works with the Hover option enabled. Normaly you need to hover your finger of that position to get the action to work but a mouse also triggers the hover.
The best way implementation of it was in [Debian noroot](https://play.google.com/store/apps/details?id=com.cuntubuntu&hl=en) for android which supported Mouses

**Comment by a1batross** [comment]
Using mouse is possible on NVIDIA SHIELD devices and(I don't tested it) on Android 7.x devices.
