### ISSUE TITLE
Using a proper mouse

### ISSUE THREAD

**Issue by Privatex86** [FWGS/xash3d-android-project#135]
Hello,

I quite like this Android port of Counter Strike and Half Life. However, I dont like using the controller for gaming it's far too big. Please can you make it so you can use the a proper mouse? Maybe you can emulate the controller for the mouse movements?

Would it be possible to change it with the Gamepad Mapping Tool?

Privatex86

:)

**Comment by a1batross** [comment]
Using mouse in CS16Client is prohibited.

Meanwhile you can use mouse in other games, such as Half-Life or mods.
If you have NVIDIA SHIELD device, you can just connect mouse, thanks to
NVIDIA extension.

Otherwise you need a root access to open raw mouse device. Use commands and
cvars starting with evdev prefix(evdev_mousepath, evdev_mouseopen,
evdev_grab).

**Comment by lbsou** [comment]
Hi, why is the use of mouse prohibited?

I currently run CS16Client but I have to clic on the screen to be able to look around.

Is it possible to avoid this?

Can we remove all the touch command on screen?

Thnak you!
